---
repos:
- repo: https://github.com/editorconfig-checker/editorconfig-checker.python
  rev: '2.7.2'
  hooks:
  - id: editorconfig-checker
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: "v3.0.0"
  hooks:
  - id: prettier
    types_or: [javascript, css]
