name: Publish to GH Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # https://github.com/actions/checkout
    - name: Checkout
      uses: actions/checkout@v4
    # https://github.com/actions/setup-node
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    # use --production to install only dependencies, not devDependencies
    - name: Install and Build
      run: |
        npm install --production
        npm run build
    - name: Upload gh-pages docs as artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: 'github-pages'
        path: dist/
  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    # We don't push to gh-pages branch
    # In Pages settings "Source" must be set to "GitHub Actions"
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: 'github-pages'
